---
- name: Install AWS CLI
  when: devtoolkit.cloud.aws_cli
  ansible.builtin.dnf:
    name: awscli2
    state: present

- name: Install Azure CLI
  when: devtoolkit.cloud.az_cli
  ansible.builtin.dnf:
    name: azure-cli
    state: present

- name: Google Cloud CLI installation
  when: devtoolkit.cloud.gcp_cli
  block:

    - name: Add Google Cloud repository
      ansible.builtin.yum_repository:
        name: google-cloud-sdk
        description: Google Cloud SDK
        baseurl: "{{ gcloud_yum_baseurl }}"
        enabled: true
        repo_gpgcheck: true
        gpgcheck: true
        gpgkey:
          - "{{ gcloud_yum_repo_key }}"
          - "{{ gcloud_yum_key }}"

    - name: Install Google Cloud CLI
      ansible.builtin.dnf:
        name: google-cloud-cli
        state: present

